
SQKM_TO_SQM = 1000*1000
M2_TO_HA = 1e-4
HA_TO_M2 = 1e4
PER_SECOND_TO_PER_DAY=86400
PER_DAY_TO_PER_SECOND=1/PER_SECOND_TO_PER_DAY
G_TO_KG=1e-3
TONS_TO_KG=1e3
KG_TO_TONS=1e-3
KG_TO_KTONS=1e-6
TONS_TO_KTONS=1e-3
KTONS_TO_TONS=1e3
KTONS_TO_KG=1e6
KG_TO_MG=1e6
TONS_TO_MG=TONS_TO_KG*KG_TO_MG
PERCENT_TO_FRACTION=1e-2

M_TO_MM = 1e3
MM_TO_M=1e-3
M_TO_KM=1e-3

CM3_TO_M3 = 1e-6
M3_TO_L=1e3
M3_TO_ML=1e-3
ML_TO_M3=1e3
ML_TO_L=ML_TO_M3*M3_TO_L
L_TO_ML=1e-6
CUMECS_TO_ML_DAY=PER_SECOND_TO_PER_DAY*M3_TO_ML

KTONS_PER_ML_TO_MG_PER_L=(KTONS_TO_KG*KG_TO_MG)/(ML_TO_L)
TONS_PER_ML_TO_MG_PER_L=(TONS_TO_KG*KG_TO_MG)/(ML_TO_L)
KG_PER_ML_TO_MG_PER_L=(KG_TO_MG)/(ML_TO_L)


MM_TO_ML_PER_HA=MM_TO_M*HA_TO_M2*M3_TO_ML
